// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzjnfchbtbhdwyslhxvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6am5mY2hidGJoZHd5c2xoeHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzc0NzQsImV4cCI6MjA3MjkxMzQ3NH0.B3Isv-UHeW4JHrBtpyhpOnC-nbCiyeE-cayySt5eVnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});